service:
  name: notification_service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: sa-east-1
  stage: ${opt:stage, 'dev'}
  
functions:
  sendMail:
    handler: src/handlers/sendMail.handler

custom:
  bundle:
    linting: false
